project:
  type: website

website:
  title: "Craig Stanton"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: journal
      dark: [journal, dark.scss]
